spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
#       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#   server:
#     waitTimeInMsWhenSyncEmpty: 5
      
      
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
   
